default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: adam
  password:

development:
  <<: *default
  database: wypociny_development

test:
  <<: *default
  database: wypociny_test